on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  schedule:
    - cron:  '0 0 * * *'
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
        env:  
          IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
          IMAP_USER: ${{ secrets.IMAP_USER }}
          IMAP_PASSWORD: ${{ secrets.IMAP_PASSWORD }}
          BOOKMARK_MAIL: ${{ secrets.BOOKMARK_MAIL }}
          ALLOWED_SENDERS: ${{ secrets.ALLOWED_SENDERS }}
      - run: npm ci
      - run: npm run bookmarks
      - run: |
          git config --global user.name "sebastian-meier"
          git config --global user.email "sebastian-meier@users.noreply.github.com"
          git add src/bookmarks/\*
          git add src/assets/screenshots/\*
          git commit -m "github-actions:bookmarks"
          git push origin publication
      - run: npm run clean